server:
  port: 80
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    format:
      date-time:  yyyy-MM-dd HH:mm:ss
    static-path-pattern: /resource/**
  web:
    resources:
      static-locations: classpath:/static/,
                        classpath:/static/icon/,
                        classpath:/META-INF/resources/,
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 2
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  redis:
    #服务器地址
    host: localhost
    #端口
    port: 6379
    #数据库
    database: 0
    #超时时间
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数
        max-active: 8
        #最大连接阻塞等待时间，默认-1
        max-wait: 1000ms
        #最大空闲连接,默认8
        max-idle: 200
        #最小空闲连接,默认0
        min-idle: 0
  rabbitmq:
    host: localhost
    username: root
    password: root
    virtual-host: /
    port: 5672
    listener:
      simple:
        #消费者最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只能处理一条消息
        prefetch: 1
        #启动时是否默认启动容器，默认true
        auto-startup: true
        #被拒绝时重新进入队列
        default-requeue-rejected: true
        retry:
          #开启消费者重试模式
          enabled: true
          max-attempts: 3
          initial-interval: 5000ms
    template:
      retry:
        enabled: true
        #重试时间，默认1000ms
        initial-interval: 1000ms
        #重试最大次数。 默认3
        max-attempts: 3
        #重试最大间隔时间,默认10000ms
        max-interval: 10000ms
        #重试的间隔乘数。比如配2.0，第一次就是10s第二次20s第三次40s
        multiplier: 1
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.peak.pojo

logging:
  level:
    com.peak.mapper: debug

